### ISSUE TITLE
How does Google Maps represent locations?

### ISSUE THREAD

**Issue by grovecj** [CSSE497/pathfinder#1]

**Comment by aj-michael** [comment]
The Android Google Maps location SDK uses latitude, longitude and UTC timestamp

https://developers.google.com/android/reference/com/google/android/gms/location/LocationResult

**Comment by aj-michael** [comment]
The iOS Location Data includes latitude and longitude

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/UsingGeocoders/UsingGeocoders.html#//apple_ref/doc/uid/TP40009497-CH4-SW1

**Comment by aj-michael** [comment]
Google Maps Geocoding API converts street addresses to latitude and longitude

https://developers.google.com/maps/documentation/geocoding/intro
