### ISSUE TITLE
How should we we bucket user input?

### ISSUE THREAD

**Issue by asciimike** [CSSE497/pathfinder#11]
Cluster = Cluster\* | Commodity\* | Vehicle*

Recursive definition of a cluster, contains zero of more clusters, commodities, and/or vehicles. Permissions cascade down clusters, once granted, goes forever.

API access would look something like client.cluster('foo/bar/baz').addCommodity(), or .getRoute(). It's important that the clusters can be created on the fly, and that if someone creates 'foo/bar/baz' that 'foo' and 'foo/bar' are also created appropriately.

**Comment by robinsdm** [comment]
This was completed. :rocket:
