### ISSUE TITLE
How do we authenticate API users?

### ISSUE THREAD

**Issue by asciimike** [CSSE497/pathfinder#12]
How do we want to deal with access control?
Do we have admin permissions?
How do we separate admin from typical users?

**Comment by asciimike** [comment]
Discussion from today: OpenID spec compliant tokens, start w/email & password, permissions in the JWT to read/write certain clusters, cluster read/write permissions cascade down (higher permission given grants access to all lower clusters).

**Comment by aj-michael** [comment]
We've started a document here: [AuthN-and-AuthZ](AuthN-and-AuthZ)

**Comment by robinsdm** [comment]
The current state of authentication is located here: [Authentication](https://github.com/CSSE497/pathfinder/wiki/Authentication-and-Authorization)

**Comment by aj-michael** [comment]
This is addresses by the authentication plan in the wiki as well as the authentication-server repo.
