### ISSUE TITLE
Boats on lakes?

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder#13]
http://newsroom.uber.com/turkey/tr/2015/06/uberboat/

**Comment by asciimike** [comment]
Helicopters in Manhattan? https://www.flyblade.com/

**Comment by asciimike** [comment]
I think the important thing to consider is that all you're doing is providing the order of points as per the routing algorithm--you don't actually have to deal with turn by turn directions on the client. That's the end developers job. So if you just present waypoints for boats/helicopters/ekranoplans/etc. it's on your customers to route between them. Using Google maps is great for some land based customers, but you don't need to delve too far into which other options are available for those new markets.
