### ISSUE TITLE
Security Proposal

### ISSUE THREAD

**Issue by robinsdm** [CSSE497/pathfinder#16]
Security for our application should be at least brought up to an acceptable level by the end of the project. In order to work towards that goal, we all need to be on the same page as security goes. Also, the current idea of security isn't very secure. We need to write out a secure method of authentication and user abilities.
- ~~[ ] Create security interaction diagram.~~
- ~~[ ] Write a wiki entry about our security.~~

**Comment by robinsdm** [comment]
Hopefully, this will remove any questions regarding security or authentication, such as #12.

**Comment by robinsdm** [comment]
So here is the start of the security proposal. There are some questions that still need to be answered. Sadly, I don't have time to create a picture to describe this.

### Object Outline

The top level object that is created first is an Organization. Each Organization can have several Applications. Also, there are Developers. A Developer can be added to several Applications. The Organization can add a Developer to an Application. Organizations and Developers are all email verified and when an Application is created under an Organization it also has to be verified with an email. When an Application is created it is created with a default Cluster so you can build a Cluster, Vehicle, Commodity (CVC) tree. All Objects can be enabled or disabled.

### Keys

Each Organization will have a login and will be able to create Applications and add/remove Developers to Applications. Every Developer will also have a login but only be able to access the Clusters under the Applications they are allowed to modify. Each Cluster has an access key. If the Cluster has childern the key will give someone access to all the children. Note, Cluster keys are permanent unless regenerated. Developer and Organization keys are temporary.

### Permissions

Organizations can add/remove Developers to Applications. Developers with access to an Application can create/enable/disable/update Clusters, Vehicles, and Commodities. Non-Developers with access to a Cluster can create/enable/disable/update Vehicles and Commodities they own.

I'll finish more of this tomorrow.

**Comment by aj-michael** [comment]
@robinsdm : What is the status of the two checkboxes on this issue? If neither is complete, please push this to Sprint 5. If one is complete, please cross off the other here and file a new issue under Sprint 5 so that we can close this issue.

**Comment by robinsdm** [comment]
I'm moving it to Sprint 5. To give us a little more time to write it. Sorry, this last week has been very busy.
