### ISSUE TITLE
Security Plan

### ISSUE THREAD

**Issue by robinsdm** [CSSE497/pathfinder#17]
Moved #16 to Sprint 5.
- [x] Create security interaction diagram.
- [x] Write a wiki entry about our security.
- [ ] Finalize design.

**Comment by robinsdm** [comment]
So here is the start of the security proposal. There are some questions that still need to be answered.

### Object Outline

The top level object that is created first is an Organization. Each Organization can have several Applications. Also, there are Developers. A Developer can be added to several Applications. The Organization can add a Developer to an Application. Organizations and Developers are all email verified and when an Application is created under an Organization it also has to be verified with an email. When an Application is created it is created with a default Cluster so you can build a Cluster, Vehicle, Commodity (CVC) tree. All Objects can be enabled or disabled.

### Keys

Each Organization will have a login and will be able to create Applications and add/remove Developers to Applications. Every Developer will also have a login but only be able to access the Clusters under the Applications they are allowed to modify. Each Cluster has an access key. If the Cluster has childern the key will give someone access to all the children. Note, Cluster keys are permanent unless regenerated. Developer and Organization keys are temporary.

### Permissions

Organizations can add/remove Developers to Applications. Developers with access to an Application can create/enable/disable/update Clusters, Vehicles, and Commodities. Non-Developers with access to a Cluster can create/enable/disable/update Vehicles and Commodities they own.

**Comment by aj-michael** [comment]
Re: last sentence:

What is a "Non-Developer"? And how does a " None-Developer" obtain access to a cluster? And what do you mean by "then own"?

**Comment by robinsdm** [comment]
Sorry, it isn't done yet. This is just a copy of the old one.

**Comment by robinsdm** [comment]
# Security Plan

![Security Diagram](https://github.com/CSSE497/pathfinder/blob/gh-pages/images/security.png?raw=true)

## Definition of objects

Note, all objects are capitalized and CVC stands for Cluster Vehicle Commodity.

### Organizations

Organizations are the highest level object. Organizations are for a company to control multiple Applications and view billing data.

### Application

An Application is owned by an Organization. An Application in Pathfinder is supposed to represent the top object of a unique dataset and create a starting point for developers to build their CVC model. When an Application is created a default Cluster is also created.

### Cluster

A Cluster is a data set that contains other CVCs.

### Vehicle

A Vehicle represents a movable object that may pick-up/drop-off Commodities.

### Commodity

A Commodity represents something someone wants moved from one location to another.

### PathfinderUser

A PathfinderUser is a verified user of the Pathfinder system. PathfinderUsers are used for access control. PathfinderUsers exist with no connection to Organizations, Applications, or CVCs.

## Access Control

### PathfinderUser

A PathfinderUser may create Organizations. When you create an Organization your PathfinderUser is added as an OrganizationManager. A PathfinderUser may edit a Vehicle or Commodity assigned to them by a Developer. A PathfinderUser may view data in a Cluster or sub-Cluster they are assigned access to by a Developer.

### OrganizationManager

An OrganizationManager may add other OrganizationManagers to the Organization and view and edit Organization details. OrganizationManagers may create and edit Applications and add Developers to those Applications. OrganizationManagers also have the access abilities of Application Developers.

### Developers

Developers may create and edit CVCs.

## Registration

A user may register using any SDK with an email and password.

## Logins

A user logins in with their email and password and receives a temporary AuthToken that lasts for three hours. This AuthToken may be used in place of an email and password for authentication.

**Comment by robinsdm** [comment]
Hey guys you should review this. @aj-michael @grovecj @danhanson

**Comment by aj-michael** [comment]
How are you planning on doing email verification? Is that something you think we should be implementing?

**Comment by aj-michael** [comment]
I am confused as to what a "PathfinderUser" is. You say that they can create organization but you also say that they may register with any SDK. What do you mean registering with an  SDK?

**Comment by aj-michael** [comment]
The really big thing you're missing atm is how we are doing authorization on the socket calls.

Mike was saying on Tuesday that we need to be authenticating users of the developers apps. That is the hard part/interesting part/thing we need to present to mike next week.

**Comment by aj-michael** [comment]
We should use session cookies to keep people logged in. If we made an auth token for that, we would just be reinventing session cookies.

**Comment by robinsdm** [comment]
A PathfinderUser is a verified user. A user may be created (registering) with any of the SDKs (js, Android, iOS).

**Comment by robinsdm** [comment]
[Sessions](https://www.playframework.com/documentation/2.4.x/JavaSessionFlash) have no authentication mechanism built in to them. You still have to create tokens. The only thing sessions guarantee is that a client cannot modify it. AuthToken is just a random String of characters and an expiration date. Sessions also work for sockets, although they are a little weird, from a short search.

**Comment by robinsdm** [comment]
Email verification can come later and it isn't hard to send an email in code. It takes one line in PHP. So you should be able to do it with links in the email with a route and a token.

**Comment by robinsdm** [comment]
The application developers can set who has access to which CVCs by storing a user id. So there is no need for an application token.

**Comment by aj-michael** [comment]
I don't think we should be making users of the developers applications verify their emails with us. That's a very broken user flow. They would have to log in to the app twice.

**Comment by aj-michael** [comment]
Also I think we need to distinguish between OUR users (developers/organizations) and users of applications that happen to use pathfinder. We are not in control of the users of applications that happen to use pathfinder.

**Comment by robinsdm** [comment]
We can take out email verification, it isn't really necessary. Mike basically made it sound like we should keep track of the end users for verification reasons. It doesn't mean we control user's applications.

**Comment by aj-michael** [comment]
I agree we need to identify them in some way. I'm just hoping that we can come with a way to authenticate them that doesn't require them to log in.

One possible idea: We require that developer who use our service authenticate with Google login. I assume that as part of Google login, the developer will receive Google's token for them. Then we can just use that token to prove their identity.

**Comment by aj-michael** [comment]
Mike suggested Google Identity Toolkit: https://developers.google.com/identity/toolkit/. I think you should look at that, and see what it returns to the developer if they use it to authenticate their clients. And then maybe we could consume that output as our auth.

**Comment by robinsdm** [comment]
I'll look into it, but it will take a few hours. I have to finish part of a take home test.

**Comment by robinsdm** [comment]
I still believe just having the develop pass the email and the password to the account along to the service would be easier. It would allow developers much more freedom. Also, if you use Google's Identity Toolkit you are required to have a Google Developers Console account, which basically means it will cost you the authenticate users.

**Comment by robinsdm** [comment]
Basically, Google's Identity Toolkit overtakes all login and registration ability which isn't good for a service to impose that restriction on the developers.

**Comment by aj-michael** [comment]
I do not think we should have the developer pass us the email and password. For one, this means that the developer has to acquire the user's password. Handling passwords is generally regarded as very bad. Most services have now switched to identity providers that handle this for them.

No one wants to write their own registration. If we take username and password, we are forcing them to.

Regarding "Google's Identity Toolkit overtakes all login and registration ability": Yes, and I think that is a really really really really good thing. It simplifies our service greatly. We are already imposing Google Maps restrictions. I think we should also impose this restriction.

**Comment by robinsdm** [comment]
They don't really have to pass a password it is really just a secret. It could be anything hard to forge.

**Comment by aj-michael** [comment]
I think that "secret" should be the ID token as returned by the Google Identity Toolkit.

**Comment by robinsdm** [comment]
So if we use Google Identity Toolkit it will require the developers server to decrypt the token and then pass it to us. Since, Google saves the keys in its dev console project which we will not access to. This will definitely add a burden to the developers. For it to be secure the developers would have to decrypt google id token and then re-encrypt it with something we know about.

**Comment by aj-michael** [comment]
david please provide links and/or document this. I've read through the ios and android docs and have seen nothing about the dev needing their own server.

On top of that, the whole point of someone else authenticating for us is so that we aren't doing the decryption. At most we should be checking that a token is signed.

**Comment by aj-michael** [comment]
On closer reading, it appears the developer only needs a webserver to implement forgot password or sending emails, neither of which concern us.

https://developers.google.com/identity/toolkit/ios/quickstart

**Comment by robinsdm** [comment]
When you authenticate it sends the token to your endpoint in an encrypted format that only your server knows how to decrypt. Then you are supposed to deal with finding the user in your database. Look at [this](https://developers.google.com/identity/toolkit/web/required-endpoints).

**Comment by robinsdm** [comment]
Mobile devices don't need to be concerned about the token because it just needs to receive as session variable and send it back for every request.

**Comment by robinsdm** [comment]
Also, why would you need authentication if you didn't have a back-end server? How are you server web pages without one? It even says in the documentation you need server end points with mobile devices.

**Comment by aj-michael** [comment]
This all sounds fine to me except for one thing: we should not require them to encrypt anything to send it to us.

**Comment by aj-michael** [comment]
And there are several reasons to use authentication if you don't have a backend server:
1. Your app might show your google contacts
2. Saving user preferences in the authentication session

But for websites, you have to have a server to host the website anyways, so I don't see this as a problem

**Comment by aj-michael** [comment]
Why do we care if they decrypt the token before sending it to us?

**Comment by aj-michael** [comment]
Taken from https://developers.google.com/identity/toolkit/web/required-endpoints

When a user signs in successfully on a Identity Toolkit-enabled site, Identity Toolkit’s widgets set a cookie named “gtoken”. It is a JSON Web Token (JWT), a cryptographically-signed JSON object encoded in base 64.

The token is signed, not encrypted. Which means we don't need any keys to read it.

**Comment by aj-michael** [comment]
Furthermore, from the same page:

"When a user signs in successfully on a Identity Toolkit-enabled site, Identity Toolkit’s widgets set a cookie named “gtoken”. It is a JSON Web Token (JWT), a cryptographically-signed JSON object encoded in base 64. The Identity Toolkit JWT is very similar to an OpenID Connect ID token and we will refer to this as the Identity Toolkit ID Token. It does not conform to the OpenID Connect specification in one important way. The user_id field in an OIDC ID token is the identifier of the user at the IDP. The user_id field in the Identity Toolkit ID Token is a global identifier, unique across all IDPs,"

I think we should use that user_id field as our user id in the database.

**Comment by robinsdm** [comment]
Ok.

**Comment by robinsdm** [comment]
The current state of security that Adam and I discussed.

# Authentication

In order to use our service, a developer needs to do the following:
1. Navigate to [http://pathfinder.io](http://pathfinder.io).
2. Register a new account with Pathfinder.
3. Create a Pathfinder application and receive an API key.
4. Provide an OpenID Connect signature verifying public key to the Pathfinder application.

# Easy Authentication Flow

![Easy authentication flow diagram](https://github.com/CSSE497/pathfinder/blob/gh-pages/images/easy_flow_sequence_diagram.png?raw=true)

Note, dashed lines are HTTP requests and solid lines are socket requests.

First, the developer of the application must set the application's global permissions to allow all requests. In easy authentication flow, the developer sends the Pathfinder server the API key, application ID, cluster ID, and a signed OpenID Connect compatible JWT (different for each end-user) to open a socket. Both the API key and application ID are created when the application is created. When the request is sent the OpenID Connect JWT is verified with the provided public and a response is generated. The requested action will be performed if the user is allowed.

# Hardcore Authentication Flow

![Hardcore authentication flow diagram](https://github.com/CSSE497/pathfinder/blob/gh-pages/images/hardcore_flow_sequence_diagram.png?raw=true)

Note, dashed lines are HTTP requests and solid lines are socket requests.

First, the developer of the application must set the application's global permissions to deny all requests. In the hardcore authentication flow, the developer's server is the only place the API key is known. The developer must first verify the end-users request for Pathfinder access. The developer's server then uses their API key, application ID, and a signed OpenID Connect compatible JWT (different for each end-user) to set user permissions. The permissions only have to be set once. The developer's server then uses their API key, application ID, and a signed OpenID Connect compatible JWT to request a user key that expires. The user key is then sent to the user. A user may then request a socket with a user key, an application ID, the signed JWT, and a cluster ID. When the request is sent the OpenID Connect JWT is verified with the provided public and a response is generated. The requested action will be performed if the user has permission.

# Mixed Authentication Flow

A developer can tailor the easy and hardcore authentication flows for your service. A developer is free to allow anyone to create commodities, but require user level permissions for creating vehicles. These permissions may be intermixed. The global permissions are first checked and then the user permissions if either allow access the user has access.

**Comment by robinsdm** [comment]
@aj-michael do you believe [randomly generated UUIDs](http://docs.oracle.com/javase/7/docs/api/java/util/UUID.html#randomUUID%28%29) should suffice for IDs. There 128 bits that uses SecureRandom in the background. It does not require that the UUIDs generated are unique but very highly improbable.

**Comment by aj-michael** [comment]
yes

**Comment by robinsdm** [comment]
Should we close this?

**Comment by aj-michael** [comment]
No, I think we should update it with the current plan. If I was at a computer I would copy in the plan from yesterday's meeting agenda.

**Comment by robinsdm** [comment]
@danhanson Once, the documentation is done link to it and close the issue.

**Comment by robinsdm** [comment]
https://pathfinder.readme.io/docs/authentication
