### ISSUE TITLE
Getting Started Documentation

### ISSUE THREAD

**Issue by robinsdm** [CSSE497/pathfinder#19]
Complete the getting started documentation on readme.io
- [x] Android documentation
- [x] iOS documentation
- [x] JavaScript documentation

**Comment by aj-michael** [comment]
@robinsdm Do you have an update on this?

**Comment by robinsdm** [comment]
The main documentation is done and Android's code is added. We still need iOS and JavaScript's code now.

**Comment by aj-michael** [comment]
iOS docs are done.

Waiting on JS to close. @danhanson

**Comment by aj-michael** [comment]
Should we check the docs into version control somewhere? I'm a little worried by the fact that I don't see an obvious "history" tab on readme.io and they make it really easy to delete pages.

**Comment by robinsdm** [comment]
In the top left corner of the docs modification tool is a versions button
![selection_028](https://cloud.githubusercontent.com/assets/8726531/14772790/180ba1ec-0a70-11e6-9841-56b94af8a557.png)
.

**Comment by aj-michael** [comment]
Does that keep history on every save though? I dont think so and Im scared to test. I think that that version is supposed to indicate the version of your SDK that the docs are for. Not the revision history.
