### ISSUE TITLE
Wiki images hosted in repo

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder#3]
I know we did this in Junior project, but it feels kind of weird to me having `images/` in the GitHub repo, stored alongside code, just to host images to put in the Wikis.

Can anyone come up with a better alternative?

**Comment by grovecj** [comment]
We can host images externally in Dropbox or something and link them from there

**Comment by grovecj** [comment]
Actually, I don't have a problem having a folder for wiki assets in the top level repo. We are probably eventually going to have more than just screenshots. I can see us including various design documents, test scripts, meeting minutes, etc. in the wiki. It may make sense to keep all of these in git. Then we also get the benefit of having these documents under version control

**Comment by robinsdm** [comment]
I just put the images on git because you can't link to google drive correctly.
