### ISSUE TITLE
CRUD API Skeleton

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder#7]
- [x] Play service is created
- [x] Class objects with ORM created for commodities
- [x] Class objects with ORM created for vehicles

**Comment by aj-michael** [comment]
GitHub only allows assignments to one person, but this will be worked on by both @grovecj and @danhanson.

**Comment by grovecj** [comment]
A pull request has been submitted for this feature.
csse497/pathfinder-server#1

**Comment by grovecj** [comment]
The pull request has been merged with the dev branch

**Comment by grovecj** [comment]
pull request has been merged in
