### ISSUE TITLE
Set up database

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder#9]
- [x] Document database schema
- [x] Ensure database is JDBC compliant (for first-party Play support)
- [x] Start a database instance on GCP

**Comment by robinsdm** [comment]
Postgresql is JDBC compliant https://jdbc.postgresql.org

**Comment by robinsdm** [comment]
Database was set up on GCP it's called pathfinder-db (postgresql database) and pathfinder-db-data (data on the postgresql database).

**Comment by grovecj** [comment]
Schema documented [here](https://github.com/CSSE497/pathfinder/wiki/Database-Schema)
